### ISSUE TITLE
How to fix it?

### ISSUE THREAD

**Issue by Vanotys** [hyydsz/Boombox#1]
![image](https://github.com/hyydsz/Boombox/assets/166815960/f1ee0f74-c439-4fa3-a4d5-896965c19e37)

**Comment by hyydsz** [comment]
![20240412183445](https://github.com/hyydsz/Boombox/assets/98519858/0de0a53f-c8e1-4ef3-9dc5-5ab30e00de28)
These two files need to be placed in the same folder

**Comment by Vanotys** [comment]
thx bro)

**Comment by hyydsz** [comment]
:)
