### ISSUE TITLE
questions 

### ISSUE THREAD

**Issue by CrownScorpion** [hyydsz/Boombox#11]
Hello i have some questions about your mod. First off is there a limit on how many songs that can be on there. I am currently working on the biggest song pack and wondering about a song limit. Second is there any way you can improve the boombox for lots of songs like adding a way to go back instead of only being able to go down the list of songs? Also any chance you could make a UI for a list of songs that would be cleaner and better than clicking to the left.

**Comment by hyydsz** [comment]
1,infinite 2, I don't have enough time. It will take a few days

**Comment by CrownScorpion** [comment]
ok thank you for answering. great mod btw
