### ISSUE TITLE
Guide 

### ISSUE THREAD

**Issue by ananasoviko** [hyydsz/Boombox#3]
I encountered a problem that my ShopUtil and boombox in particular do not start. Can you make a video guide on how to install a boombox and a ShopUtil?
At the same time, I fulfilled all the conditions

**Comment by hyydsz** [comment]
Do you only install these two plugins?

**Comment by ananasoviko** [comment]
> Вы устанавливаете только эти два плагина?
I still have BeplnEx
But at the moment I want to install boombox and ShopUtill, but nothing works for me

**Comment by ananasoviko** [comment]
sorry for my bad English, I speak Russian

**Comment by hyydsz** [comment]
[ModPack.zip](https://github.com/hyydsz/Boombox/files/14970469/ModPack.zip)
Unzip this compressed file to the game directory. like this:
![20240414191902](https://github.com/hyydsz/Boombox/assets/98519858/6881a0cd-c1f1-4c4b-bd40-b71cf8e32d04)

**Comment by hyydsz** [comment]
It works?

**Comment by ananasoviko** [comment]
wait a second

**Comment by ananasoviko** [comment]
Yes it works
But just the last question, is it possible to make it free?

**Comment by hyydsz** [comment]
Which free are you referring to

**Comment by ananasoviko** [comment]
So that the boombox costs $0 and not $100, or this is not possible

**Comment by hyydsz** [comment]
Open the BepInEx/config/hyydsz-Boombox.cfg File.
 Set **BoomboxPrice** To 0.

**Comment by ananasoviko** [comment]
Thanks You
