### ISSUE TITLE
My friends can't hear boombox

### ISSUE THREAD

**Issue by qseftgi** [hyydsz/Boombox#4]
Do you know why my friends can't hear my music in the boombox?

**Comment by hyydsz** [comment]
Do you and your friend install same music?

**Comment by qseftgi** [comment]
So they have to download the exactly same mp3 file as I downloaded in order for them to hear it?

**Comment by hyydsz** [comment]
yes

**Comment by qseftgi** [comment]
Damn thats pretty unlucky, my friends are too lazy to download mp3 files. Wish it would play in game like connecting through your mic or something but thanks.

**Comment by hyydsz** [comment]
I will try to do it
