### ISSUE TITLE
i don't understand how to put the songs 

### ISSUE THREAD

**Issue by cuchongo** [hyydsz/Boombox#5]

**Comment by hyydsz** [comment]
Put your music in **BepInEx/plugins/Custom Songs** folder

**Comment by cuchongo** [comment]
but do i put the mp3

**Comment by cuchongo** [comment]
and i dont have a custom song folder

**Comment by hyydsz** [comment]
It supports mp3. You need to open the game once or create a new folder

**Comment by gabbigamers** [comment]
i also dont like how when i try to switch songs it doesnt do anything and when i start the game the music files get deleted.

**Comment by hyydsz** [comment]
> i also dont like how when i try to switch songs it doesnt do anything and when i start the game the music files get deleted.

It's not my mod that deletes music files.

**Comment by LeotasD** [comment]
> Put your music in **BepInEx/plugins/Custom Songs** folder

There's no BepInEx folder if you use Thunderstore to install the mod.  So how is it possible to add sounds this way?

**Comment by gabbigamers** [comment]
I mean when i used another mod that was a fork of yours, it stopped deleting the music files.

**Comment by gabbigamers** [comment]
Also either sillyitems or extraitems makes it so you cant pickup the radio since it deletes itself.

**Comment by hyydsz** [comment]
> > Put your music in **BepInEx/plugins/Custom Songs** folder
> 
> There's no BepInEx folder if you use Thunderstore to install the mod. So how is it possible to add sounds this way?

![image](https://github.com/hyydsz/Boombox/assets/98519858/fbb63a79-035b-41e5-bb96-dc0949eff80e)
I using r2modman, which should be similar to Thunderstore.
Check here to open BepInEx folder

**Comment by hyydsz** [comment]
> I mean when i used another mod that was a fork of yours, it stopped deleting the music files.

BoomboxMusicShare will delete all music when opening the game.
The solution is very simple, You can create a folder with any name in the Plugin folder and copy your music into it.

**Comment by hyydsz** [comment]
> Also either sillyitems or extraitems makes it so you cant pickup the radio since it deletes itself.

The ShopItem library I am using has compatibility issues with these mods.
Just remove the volume control and it will solve the problem.

**Comment by hyydsz** [comment]
> Also either sillyitems or extraitems makes it so you cant pickup the radio since it deletes itself.

This is a fixed version.
[Release.zip](https://github.com/hyydsz/Boombox/files/15058658/Release.zip)

**Comment by gabbigamers** [comment]
Alright thanks! :D

**Comment by Mevillius** [comment]
> BoomboxMusicShare will delete all music when opening the game. The solution is very simple, You can create a folder with any name in the Plugin folder and copy your music into it.

I am having the same issues, what i tried:
putting the folder with all the songs in BoomboxMusicShare folder, plugins folder and Custom Songs folder.

of course the music folder has a name different to "Custom Songs"

aaand "NO MUSIC" in the boombox each time i retry.

[heres](https://thunderstore.io/c/content-warning/p/omgg_team/CW_omgg/) the songs I'm trying to put in the boombox

**Comment by hyydsz** [comment]
> > BoomboxMusicShare will delete all music when opening the game. The solution is very simple, You can create a folder with any name in the Plugin folder and copy your music into it.
> 
> I am having the same issues, what i tried: putting the folder with all the songs in BoomboxMusicShare folder, plugins folder and Custom Songs folder.
> 
> of course the music folder has a name different to "Custom Songs"
> 
> aaand "NO MUSIC" in the boombox each time i retry.
> 
> [heres](https://thunderstore.io/c/content-warning/p/omgg_team/CW_omgg/) the songs I'm trying to put in the boombox

i need your log file

**Comment by Mevillius** [comment]
> i need your log file

sure, [here](https://hastebin.com/share/bofilafiba.yaml)

**Comment by LimeSkillZ** [comment]
For some reason, custom songs don't seem to load the first time you start the game, even though they're being moved to the Custom Songs folder correctly. You might have to restart your game once.

**Comment by hyydsz** [comment]
> > i need your log file
> 
> sure, [here](https://hastebin.com/share/bofilafiba.yaml)

Looks like BoomboxMusicShare didn't find the music file. 
You need put your music files into BepInEx/plugins/NameThisWhatever/Custom Songs/
maybe

**Comment by Mevillius** [comment]
> Looks like BoomboxMusicShare didn't find the music file. You need put your music files into BepInEx/plugins/NameThisWhatever/Custom Songs/ maybe

'NO MUSIC' still, sincerely losing hope that this might work

**Comment by LimeSkillZ** [comment]
Make sure that both the Boombox mod and BoomboxMusicShare are on the latest version. Are the music files in .wav, .mp3, or .ogg format? Other than those two things I'm not exactly sure what the problem is. I've posted some pictures below to show what your folders should look like.

This is the "plugins" folder
![Plugins Folder](https://github.com/hyydsz/Boombox/assets/38006438/fad5986d-af87-4b08-b90d-8bddd3f01ffd)

This is inside the "music" folder
![Music Folder](https://github.com/hyydsz/Boombox/assets/38006438/71bfbb91-3c13-468f-a1a5-787d77173287)

This is inside the "Custom Songs" folder, which was inside the "music" folder
![Custom Songs](https://github.com/hyydsz/Boombox/assets/38006438/e18350c5-b476-45a2-a622-443c38e5830f)

After launching the game, a new "Custom Songs" folder appears in the "plugins" folder, which contains the three songs I had in the image before. Testing this in-game works how it should too.

**Comment by Mevillius** [comment]
> Make sure that both the Boombox mod and BoomboxMusicShare are on the latest version. Are the music files in .wav, .mp3, or .ogg format? Other than those two things I'm not exactly sure what the problem is. I've posted some pictures below to show what your folders should look like.
> 
> This is the "plugins" folder ![Plugins Folder](https://private-user-images.githubusercontent.com/38006438/329112447-fad5986d-af87-4b08-b90d-8bddd3f01ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODE2NjUsIm5iZiI6MTcxNTI4MTM2NSwicGF0aCI6Ii8zODAwNjQzOC8zMjkxMTI0NDctZmFkNTk4NmQtYWY4Ny00YjA4LWI5MGQtOGJkZGQzZjAxZmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE5MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzUwZDI0MGY1M2U4Y2FjNDMyODFjMzYzZDhhMWRmZWU1YjFiOTlmN2EzMzY2NDg3ZWM5OTZlZDI5YTU2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fod1yPjD34VKO-p5ZAoDxbUzBsuqff7gw_8yPa4hM4)
> 
> This is inside the "music" folder ![Music Folder](https://private-user-images.githubusercontent.com/38006438/329112583-71bfbb91-3c13-468f-a1a5-787d77173287.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODE2NjUsIm5iZiI6MTcxNTI4MTM2NSwicGF0aCI6Ii8zODAwNjQzOC8zMjkxMTI1ODMtNzFiZmJiOTEtM2MxMy00NjhmLWExYTUtNzg3ZDc3MTczMjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE5MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZjAxNTAyM2YxZTIwNzI1ZDYwM2ZlZDZhMjYyZmMyY2IxNmI4YzVmODI4YTQwYjVkYWI2MjFiNDdjZjE2MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezkzVyC64-pVo2oulBBKfXBzslAai4Iwd8bsTUyI7_M)
> 
> This is inside the "Custom Songs" folder, which was inside the "music" folder ![Custom Songs](https://private-user-images.githubusercontent.com/38006438/329112646-e18350c5-b476-45a2-a622-443c38e5830f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODE2NjUsIm5iZiI6MTcxNTI4MTM2NSwicGF0aCI6Ii8zODAwNjQzOC8zMjkxMTI2NDYtZTE4MzUwYzUtYjQ3Ni00NWEyLWE2MjItNDQzYzM4ZTU4MzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE5MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YWY3ODk1OGU1YjhlMGQ0MDcxNjNmMjBmOTU3MDRhOThlNDA2Njk5NDRmNTlkNzdhYzc1NmU1NWFiODNkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBGIAv0EAFSXwvNYkb5xqzEpSW-HGjqpBMyclz5vv-8)
> 
> After launching the game, a new "Custom Songs" folder appears in the "plugins" folder, which contains the three songs I had in the image before. Testing this in-game works how it should too.

it does not work..

also yes, mods are updated and all files are .mp3

**Comment by hyydsz** [comment]
> > Make sure that both the Boombox mod and BoomboxMusicShare are on the latest version. Are the music files in .wav, .mp3, or .ogg format? Other than those two things I'm not exactly sure what the problem is. I've posted some pictures below to show what your folders should look like.
> > This is the "plugins" folder ![Plugins Folder](https://private-user-images.githubusercontent.com/38006438/329112447-fad5986d-af87-4b08-b90d-8bddd3f01ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODE2NjUsIm5iZiI6MTcxNTI4MTM2NSwicGF0aCI6Ii8zODAwNjQzOC8zMjkxMTI0NDctZmFkNTk4NmQtYWY4Ny00YjA4LWI5MGQtOGJkZGQzZjAxZmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE5MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzUwZDI0MGY1M2U4Y2FjNDMyODFjMzYzZDhhMWRmZWU1YjFiOTlmN2EzMzY2NDg3ZWM5OTZlZDI5YTU2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fod1yPjD34VKO-p5ZAoDxbUzBsuqff7gw_8yPa4hM4)
> > This is inside the "music" folder ![Music Folder](https://private-user-images.githubusercontent.com/38006438/329112583-71bfbb91-3c13-468f-a1a5-787d77173287.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODE2NjUsIm5iZiI6MTcxNTI4MTM2NSwicGF0aCI6Ii8zODAwNjQzOC8zMjkxMTI1ODMtNzFiZmJiOTEtM2MxMy00NjhmLWExYTUtNzg3ZDc3MTczMjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE5MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZjAxNTAyM2YxZTIwNzI1ZDYwM2ZlZDZhMjYyZmMyY2IxNmI4YzVmODI4YTQwYjVkYWI2MjFiNDdjZjE2MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezkzVyC64-pVo2oulBBKfXBzslAai4Iwd8bsTUyI7_M)
> > This is inside the "Custom Songs" folder, which was inside the "music" folder ![Custom Songs](https://private-user-images.githubusercontent.com/38006438/329112646-e18350c5-b476-45a2-a622-443c38e5830f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODE2NjUsIm5iZiI6MTcxNTI4MTM2NSwicGF0aCI6Ii8zODAwNjQzOC8zMjkxMTI2NDYtZTE4MzUwYzUtYjQ3Ni00NWEyLWE2MjItNDQzYzM4ZTU4MzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE5MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YWY3ODk1OGU1YjhlMGQ0MDcxNjNmMjBmOTU3MDRhOThlNDA2Njk5NDRmNTlkNzdhYzc1NmU1NWFiODNkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBGIAv0EAFSXwvNYkb5xqzEpSW-HGjqpBMyclz5vv-8)
> > After launching the game, a new "Custom Songs" folder appears in the "plugins" folder, which contains the three songs I had in the image before. Testing this in-game works how it should too.
> 
> it does not work..
> 
> also yes, mods are updated and all files are .mp3

you can uninstall BoomboxMusicShare and copy all music files to `plugins/Custom Songs`

**Comment by Mevillius** [comment]
> you can uninstall BoomboxMusicShare and copy all music files to `plugins/Custom Songs`

now it does work, thank you.
