### ISSUE TITLE
Is it possible to add in a MML playback to the boombox?

### ISSUE THREAD

**Issue by dra6o0n** [hyydsz/Boombox#6]
This is so that when users who may not have the mod is in the vicinity they can still hear this sort of music, played using midi on the computer. Or perhaps those who has the mod but not the file can hear it due to the mod containing the library necessary for playback.

The game basically 'parses' text in the form of MML notation and plays musical tones and noises of instruments accordingly.
An example of what MML is and how people make it. The 3mle editor itself comes with the dls file which is a [soundfont](https://en.wikipedia.org/wiki/SoundFont) file.
https://www.youtube.com/watch?v=17GUXTfji60

Because with the current implementation, it's only client sided music that can be heard.

**Comment by dra6o0n** [comment]
Basically, text based sharing of MML is faster than 'syncing' midi files from one player to another, and safer as well.
So other players would 'receive' the data and hear the playback immediately in real time as the boombox would be indicating which character it is currently at, so it syncs to other players to hear it in real time.

**Comment by hyydsz** [comment]
This will loss of sound quality.
It is the best to install exactly the same music on the client and the host

**Comment by hyydsz** [comment]
I've try it. It's not like voice, It requires a very stable network. This can easily cause music lag. This is not ideal
