### ISSUE TITLE
boombox not possible to collect

### ISSUE THREAD

**Issue by AdrianMarczak** [hyydsz/Boombox#7]
the boombox is buyable and if you buy it it will send it to you but if you try to collect it it disapears.

**Comment by hyydsz** [comment]
Is there an error in the log

**Comment by megatensuke** [comment]
![x1](https://github.com/hyydsz/Boombox/assets/131615947/9dee068f-9b1a-44ae-a50a-777980652239)

**Comment by hyydsz** [comment]
Are you using the latest version of mods?

**Comment by megatensuke** [comment]
Hey bro, I read your other reply about "ExtraItems", I had that mod installed and your fix solved the problem. Thanks!

**Comment by hyydsz** [comment]
> Hey bro, I read your other reply about "ExtraItems", I had that mod installed and your fix solved the problem. Thanks!

There are some problem with the "ExtraItems", please do not use it

**Comment by megatensuke** [comment]
Yeah, I took that mod out, I rather your mod works since it's a must :D
